### ISSUE TITLE
Direction code breaks if the user selects geometry type as GeoJSON

### ISSUE THREAD

**Issue by thearavind** [ryankurte/go-mapbox#12]
In the direction & map matching response the `Geometry` field will be of the type [lineString object](https://tools.ietf.org/html/rfc7946#appendix-A.2) or Encoded string based on the `GeometryType` in the request parameter.

This has also been mentioned in the [mapbox document](https://www.mapbox.com/api-documentation/#route-object)

But in the response struct we specify that the geometry field is of type `string`  [go-mapbox/lib/directions/types.go](https://github.com/ryankurte/go-mapbox/blob/master/lib/directions/types.go#L25) 

This breaks the code when the `GeometryType` is lineString .

Steps to reproduce the error

- Change line no 37 in [go-mapbox/lib/map_matching/map_matching_test.go](https://github.com/ryankurte/go-mapbox/blob/master/lib/map_matching/map_matching_test.go#L37) to ```opts.SetGeometries(GeometryGeojson)``` and run the test

How can we overcome this issue? Expecting some suggestions from you @ryankurte

**Comment by ryankurte** [comment]
Had a bash at it using interface{} -> map[string]interface{} -> [] interface{} -> float64. It's a bit mad / would love to know of a better way, but seems to work?
