### ISSUE TITLE
Directions always result in a segfault

### ISSUE THREAD

**Issue by cmorent** [ryankurte/go-mapbox#16]
Hello there! I am testing go-mapbox and I have some issues with the Directions part of it. When I try the given example:

```
var directionOpts directions.RequestOpts

locs := []base.Location{{-122.42, 37.78}, {-77.03, 38.91}}

directions, err := mapBox.Directions.GetDirections(locs, directions.RoutingCycling, &directionOpts)
```

It always results in a segfault like this:

```
$ go run test.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1204f1b]

goroutine 1 [running]:
github.com/ryankurte/go-mapbox/lib/base.(*Base).QueryBase(0xc4200dc320, 0xc420016190, 0x47, 0xc42004fe08, 0x123d400, 0xc42005a200, 0x0, 0x0)
	/Users/cmorent/go/src/github.com/ryankurte/go-mapbox/lib/base/base.go:101 +0xcb
github.com/ryankurte/go-mapbox/lib/base.(*Base).Query(0xc4200dc320, 0x12ad13b, 0xa, 0x12abd84, 0x2, 0x12ae073, 0xe, 0xc42001e180, 0x2a, 0xc42004fe08, ...)
	/Users/cmorent/go/src/github.com/ryankurte/go-mapbox/lib/base/base.go:138 +0x209
github.com/ryankurte/go-mapbox/lib/directions.(*Directions).GetDirections(0xc42000e090, 0xc42004feb8, 0x2, 0x2, 0x12ae073, 0xe, 0xc42005a1c0, 0x1, 0xc42004ff30, 0x121d733)
	/Users/cmorent/go/src/github.com/ryankurte/go-mapbox/lib/directions/directions.go:140 +0x350
main.main()
	/Users/cmorent/go/src/github.com/cmorent/tests/test.go:29 +0x2be
exit status 2
```

Am I doing something wrong here? Thanks !

**Comment by cmorent** [comment]
My bad, I was trying to do something very silly with the access_token... Sorry for the noise!

**Comment by ryankurte** [comment]
No worries! May I ask what it was? If it's easy to improve the error or document it might help someone else ^_^

**Comment by cmorent** [comment]
Sure, I was trying to get my access token from a non existing environment variable! Maybe a warning/error when trying to instantiate the MapBox client would help for such a case?

**Comment by ryankurte** [comment]
Sorry this took so long to reply to.

Most definitely a case for an error, I'd be very happy to accept a PR to add that (or will get to it when I can). Would probably add an error case [here](https://github.com/ryankurte/go-mapbox/blob/b922f5e38d5528f9f1c98d09190b6a61e5c69428/lib/base/base.go#L35) and bubble it up through the API.

**Comment by cmorent** [comment]
Ok, I'm on it! Thanks for your reply!

**Comment by cmorent** [comment]
Well done in #20 !

**Comment by ryankurte** [comment]
And merged, thanks!
